### ISSUE TITLE
Nock beta releases

### ISSUE THREAD

**Issue by paulmelnikow** [ikatyang/jest-playback#356]
Hi! We've started making beta releases toward the next major release of nock. Would you be up for giving one of them a shot in some tests for this library to help us ensure compatibility?

[![npm](https://img.shields.io/npm/v/nock.svg)][npmjs]
[![npm@beta](https://img.shields.io/npm/v/nock/beta.svg)][npmjs]

[npmjs]: https://www.npmjs.com/package/nock

Note that v11, when it's released, will drop support for Node 6.

**Comment by defrex** [comment]
I opened a PR for v11

https://github.com/ikatyang/jest-playback/pull/411
